### ISSUE TITLE
how to get acyclic rgfa

### ISSUE THREAD

**Issue by 8banzhuan** [at-cg/minichain#1]
hello,Thank you for your software，I go to the link provided in your readme to find the data，But I only found fasta and fastq data
Do I need to build an acid rgfa with your software？The graph built by minigraph you know doesn't work in your software，Or where can I download the available data directly
look forward to your reply

**Comment by gsc74** [comment]
The acyclic rGFA graphs can be generated with `--inv=no` parameter with the `minigraph`.
Commands are provided in the [generate_graph.sh](https://github.com/at-cg/minichain/blob/master/data/generate_graphs.sh) file.
Moreover, in the [data](https://github.com/at-cg/minichain/blob/master/data) folder following commands can be used to download the data, build the graphs, simulate and map reads and evaluate the results. 
```
sh reproduce.sh
cd compare_errors
sh run.sh
```
